# Generated by Django 3.0.3 on 2020-02-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen',
            name='max_cooks',
            field=models.IntegerField(),
        ),
    ]
