# Generated by Django 3.0.3 on 2020-02-15 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20200215_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchen',
            name='max_cooks',
        ),
    ]
