# Generated by Django 3.0.3 on 2020-02-15 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0002_auto_20200215_1755'),
        ('authentication', '0003_auto_20200215_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(upload_to='items')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('COOKING', 'COOKING'), ('COMPLETED', 'COMPLETED'), ('DECLINED', 'DECLINED')], default='PENDING', max_length=10)),
                ('total_price', models.FloatField()),
                ('chef', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chefs_order', to='authentication.ChefProfile')),
                ('items', models.ManyToManyField(to='ordering.Item')),
                ('kitchen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kitchens_order', to='management.Kitchen')),
            ],
        ),
    ]
