# Generated by Django 3.0.3 on 2020-02-15 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20200215_1911'),
        ('management', '0002_auto_20200215_1755'),
        ('ordering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='authentication.CustomerProfile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='chef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='authentication.ChefProfile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, to='ordering.Item'),
        ),
        migrations.AlterField(
            model_name='order',
            name='kitchen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='management.Kitchen'),
        ),
    ]
