# Generated by Django 3.0.3 on 2020-02-16 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_shift_menu_items'),
        ('ordering', '0004_auto_20200216_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shift',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='management.Shift'),
            preserve_default=False,
        ),
    ]
