# Generated by Django 3.0.3 on 2020-02-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20200215_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefprofile',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
