# Generated by Django 3.0.3 on 2020-02-15 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20200215_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefprofile',
            name='percentage',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
